name: multiple_window_example
description: "Multiple Window Example"
publish_to: "none"
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.11.0-57.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  nativeapi:
    path: ../../packages/nativeapi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
